# Generated by Django 3.2.10 on 2021-12-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('actors', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=30)),
                ('reader', models.CharField(blank=True, max_length=100)),
                ('media_type', models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIBLE', 'Audible')], max_length=10)),
                ('audience', models.CharField(blank=True, max_length=30)),
                ('promo_img', models.ImageField(blank=True, upload_to='')),
                ('promo_desc', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=20)),
                ('name_last', models.CharField(max_length=25)),
                ('cell_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('year_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIBLE', 'Audible')], max_length=10)),
                ('source', models.CharField(blank=True, max_length=25)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('mycomment', models.CharField(blank=True, max_length=100)),
                ('recommended_by', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('STARTED', 'Started'), ('WISHLIST', 'Wish List')], max_length=10)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('media', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.media')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='media.user')),
            ],
        ),
    ]
