# Generated by Django 3.2.10 on 2022-01-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='media_type',
        ),
    ]
